apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sdfsfsdfsdffs
  title: Sdflkjsdfkljslf
  description: A static HTML website. Just like the good old days.
  links:
    - url: https://roadiehq.github.io/sdfsfsdfsdffs/
      title: Live website
  annotations:
    github.com/project-slug: roadiehq/sdfsfsdfsdffs
spec:
  type: website
  owner: user:dtuite
  lifecycle: experimental
